// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arrive.proto

package com.protobuf;

public final class Arrive {
  private Arrive() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface arrive_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:arrive_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 player_id = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>optional uint32 player_id = 1;</code>
     */
    int getPlayerId();

    /**
     * <code>optional uint32 army_id = 2;</code>
     */
    boolean hasArmyId();
    /**
     * <code>optional uint32 army_id = 2;</code>
     */
    int getArmyId();

    /**
     * <code>optional int32 to_x = 3;</code>
     */
    boolean hasToX();
    /**
     * <code>optional int32 to_x = 3;</code>
     */
    int getToX();

    /**
     * <code>optional int32 to_y = 4;</code>
     */
    boolean hasToY();
    /**
     * <code>optional int32 to_y = 4;</code>
     */
    int getToY();
  }
  /**
   * Protobuf type {@code arrive_request}
   */
  public static final class arrive_request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:arrive_request)
      arrive_requestOrBuilder {
    // Use arrive_request.newBuilder() to construct.
    private arrive_request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private arrive_request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final arrive_request defaultInstance;
    public static arrive_request getDefaultInstance() {
      return defaultInstance;
    }

    public arrive_request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private arrive_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              armyId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              toX_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              toY_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.Arrive.internal_static_arrive_request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.Arrive.internal_static_arrive_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.Arrive.arrive_request.class, com.protobuf.Arrive.arrive_request.Builder.class);
    }

    public static com.google.protobuf.Parser<arrive_request> PARSER =
        new com.google.protobuf.AbstractParser<arrive_request>() {
      public arrive_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new arrive_request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<arrive_request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>optional uint32 player_id = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 player_id = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int ARMY_ID_FIELD_NUMBER = 2;
    private int armyId_;
    /**
     * <code>optional uint32 army_id = 2;</code>
     */
    public boolean hasArmyId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 army_id = 2;</code>
     */
    public int getArmyId() {
      return armyId_;
    }

    public static final int TO_X_FIELD_NUMBER = 3;
    private int toX_;
    /**
     * <code>optional int32 to_x = 3;</code>
     */
    public boolean hasToX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 to_x = 3;</code>
     */
    public int getToX() {
      return toX_;
    }

    public static final int TO_Y_FIELD_NUMBER = 4;
    private int toY_;
    /**
     * <code>optional int32 to_y = 4;</code>
     */
    public boolean hasToY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 to_y = 4;</code>
     */
    public int getToY() {
      return toY_;
    }

    private void initFields() {
      playerId_ = 0;
      armyId_ = 0;
      toX_ = 0;
      toY_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, armyId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, toX_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, toY_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, armyId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, toX_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, toY_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.Arrive.arrive_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.Arrive.arrive_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.Arrive.arrive_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.Arrive.arrive_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.Arrive.arrive_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.Arrive.arrive_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.Arrive.arrive_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.Arrive.arrive_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.Arrive.arrive_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.Arrive.arrive_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.Arrive.arrive_request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code arrive_request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:arrive_request)
        com.protobuf.Arrive.arrive_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.Arrive.internal_static_arrive_request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.Arrive.internal_static_arrive_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.Arrive.arrive_request.class, com.protobuf.Arrive.arrive_request.Builder.class);
      }

      // Construct using com.protobuf.Arrive.arrive_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        armyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        toX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        toY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.Arrive.internal_static_arrive_request_descriptor;
      }

      public com.protobuf.Arrive.arrive_request getDefaultInstanceForType() {
        return com.protobuf.Arrive.arrive_request.getDefaultInstance();
      }

      public com.protobuf.Arrive.arrive_request build() {
        com.protobuf.Arrive.arrive_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.Arrive.arrive_request buildPartial() {
        com.protobuf.Arrive.arrive_request result = new com.protobuf.Arrive.arrive_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.armyId_ = armyId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.toX_ = toX_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toY_ = toY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.Arrive.arrive_request) {
          return mergeFrom((com.protobuf.Arrive.arrive_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.Arrive.arrive_request other) {
        if (other == com.protobuf.Arrive.arrive_request.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasArmyId()) {
          setArmyId(other.getArmyId());
        }
        if (other.hasToX()) {
          setToX(other.getToX());
        }
        if (other.hasToY()) {
          setToY(other.getToY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.Arrive.arrive_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.Arrive.arrive_request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int playerId_ ;
      /**
       * <code>optional uint32 player_id = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 player_id = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional uint32 player_id = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 player_id = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      private int armyId_ ;
      /**
       * <code>optional uint32 army_id = 2;</code>
       */
      public boolean hasArmyId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 army_id = 2;</code>
       */
      public int getArmyId() {
        return armyId_;
      }
      /**
       * <code>optional uint32 army_id = 2;</code>
       */
      public Builder setArmyId(int value) {
        bitField0_ |= 0x00000002;
        armyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 army_id = 2;</code>
       */
      public Builder clearArmyId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        armyId_ = 0;
        onChanged();
        return this;
      }

      private int toX_ ;
      /**
       * <code>optional int32 to_x = 3;</code>
       */
      public boolean hasToX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 to_x = 3;</code>
       */
      public int getToX() {
        return toX_;
      }
      /**
       * <code>optional int32 to_x = 3;</code>
       */
      public Builder setToX(int value) {
        bitField0_ |= 0x00000004;
        toX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 to_x = 3;</code>
       */
      public Builder clearToX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        toX_ = 0;
        onChanged();
        return this;
      }

      private int toY_ ;
      /**
       * <code>optional int32 to_y = 4;</code>
       */
      public boolean hasToY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 to_y = 4;</code>
       */
      public int getToY() {
        return toY_;
      }
      /**
       * <code>optional int32 to_y = 4;</code>
       */
      public Builder setToY(int value) {
        bitField0_ |= 0x00000008;
        toY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 to_y = 4;</code>
       */
      public Builder clearToY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toY_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:arrive_request)
    }

    static {
      defaultInstance = new arrive_request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:arrive_request)
  }

  public interface arriveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:arrive)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 player_id = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>optional uint32 player_id = 1;</code>
     */
    int getPlayerId();

    /**
     * <code>optional uint32 army_id = 2;</code>
     */
    boolean hasArmyId();
    /**
     * <code>optional uint32 army_id = 2;</code>
     */
    int getArmyId();

    /**
     * <code>optional int32 code = 3;</code>
     */
    boolean hasCode();
    /**
     * <code>optional int32 code = 3;</code>
     */
    int getCode();

    /**
     * <code>optional uint32 interval = 4;</code>
     */
    boolean hasInterval();
    /**
     * <code>optional uint32 interval = 4;</code>
     */
    int getInterval();

    /**
     * <code>optional int32 from_x = 5;</code>
     */
    boolean hasFromX();
    /**
     * <code>optional int32 from_x = 5;</code>
     */
    int getFromX();

    /**
     * <code>optional int32 from_y = 6;</code>
     */
    boolean hasFromY();
    /**
     * <code>optional int32 from_y = 6;</code>
     */
    int getFromY();
  }
  /**
   * Protobuf type {@code arrive}
   */
  public static final class arrive extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:arrive)
      arriveOrBuilder {
    // Use arrive.newBuilder() to construct.
    private arrive(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private arrive(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final arrive defaultInstance;
    public static arrive getDefaultInstance() {
      return defaultInstance;
    }

    public arrive getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private arrive(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              armyId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              code_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              interval_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              fromX_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              fromY_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.Arrive.internal_static_arrive_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.Arrive.internal_static_arrive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.Arrive.arrive.class, com.protobuf.Arrive.arrive.Builder.class);
    }

    public static com.google.protobuf.Parser<arrive> PARSER =
        new com.google.protobuf.AbstractParser<arrive>() {
      public arrive parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new arrive(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<arrive> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>optional uint32 player_id = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 player_id = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int ARMY_ID_FIELD_NUMBER = 2;
    private int armyId_;
    /**
     * <code>optional uint32 army_id = 2;</code>
     */
    public boolean hasArmyId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 army_id = 2;</code>
     */
    public int getArmyId() {
      return armyId_;
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private int code_;
    /**
     * <code>optional int32 code = 3;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 code = 3;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int INTERVAL_FIELD_NUMBER = 4;
    private int interval_;
    /**
     * <code>optional uint32 interval = 4;</code>
     */
    public boolean hasInterval() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 interval = 4;</code>
     */
    public int getInterval() {
      return interval_;
    }

    public static final int FROM_X_FIELD_NUMBER = 5;
    private int fromX_;
    /**
     * <code>optional int32 from_x = 5;</code>
     */
    public boolean hasFromX() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 from_x = 5;</code>
     */
    public int getFromX() {
      return fromX_;
    }

    public static final int FROM_Y_FIELD_NUMBER = 6;
    private int fromY_;
    /**
     * <code>optional int32 from_y = 6;</code>
     */
    public boolean hasFromY() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 from_y = 6;</code>
     */
    public int getFromY() {
      return fromY_;
    }

    private void initFields() {
      playerId_ = 0;
      armyId_ = 0;
      code_ = 0;
      interval_ = 0;
      fromX_ = 0;
      fromY_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, armyId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, code_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, interval_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, fromX_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, fromY_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, armyId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, code_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, interval_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, fromX_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, fromY_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.Arrive.arrive parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.Arrive.arrive parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.Arrive.arrive parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.Arrive.arrive parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.Arrive.arrive parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.Arrive.arrive parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.Arrive.arrive parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.Arrive.arrive parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.Arrive.arrive parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.Arrive.arrive parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.Arrive.arrive prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code arrive}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:arrive)
        com.protobuf.Arrive.arriveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.Arrive.internal_static_arrive_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.Arrive.internal_static_arrive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.Arrive.arrive.class, com.protobuf.Arrive.arrive.Builder.class);
      }

      // Construct using com.protobuf.Arrive.arrive.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        armyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        interval_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        fromX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        fromY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.Arrive.internal_static_arrive_descriptor;
      }

      public com.protobuf.Arrive.arrive getDefaultInstanceForType() {
        return com.protobuf.Arrive.arrive.getDefaultInstance();
      }

      public com.protobuf.Arrive.arrive build() {
        com.protobuf.Arrive.arrive result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.Arrive.arrive buildPartial() {
        com.protobuf.Arrive.arrive result = new com.protobuf.Arrive.arrive(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.armyId_ = armyId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.interval_ = interval_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fromX_ = fromX_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.fromY_ = fromY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.Arrive.arrive) {
          return mergeFrom((com.protobuf.Arrive.arrive)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.Arrive.arrive other) {
        if (other == com.protobuf.Arrive.arrive.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasArmyId()) {
          setArmyId(other.getArmyId());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasInterval()) {
          setInterval(other.getInterval());
        }
        if (other.hasFromX()) {
          setFromX(other.getFromX());
        }
        if (other.hasFromY()) {
          setFromY(other.getFromY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.Arrive.arrive parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.Arrive.arrive) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int playerId_ ;
      /**
       * <code>optional uint32 player_id = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 player_id = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional uint32 player_id = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 player_id = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      private int armyId_ ;
      /**
       * <code>optional uint32 army_id = 2;</code>
       */
      public boolean hasArmyId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 army_id = 2;</code>
       */
      public int getArmyId() {
        return armyId_;
      }
      /**
       * <code>optional uint32 army_id = 2;</code>
       */
      public Builder setArmyId(int value) {
        bitField0_ |= 0x00000002;
        armyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 army_id = 2;</code>
       */
      public Builder clearArmyId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        armyId_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 3;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 code = 3;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 3;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000004;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 3;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = 0;
        onChanged();
        return this;
      }

      private int interval_ ;
      /**
       * <code>optional uint32 interval = 4;</code>
       */
      public boolean hasInterval() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 interval = 4;</code>
       */
      public int getInterval() {
        return interval_;
      }
      /**
       * <code>optional uint32 interval = 4;</code>
       */
      public Builder setInterval(int value) {
        bitField0_ |= 0x00000008;
        interval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 interval = 4;</code>
       */
      public Builder clearInterval() {
        bitField0_ = (bitField0_ & ~0x00000008);
        interval_ = 0;
        onChanged();
        return this;
      }

      private int fromX_ ;
      /**
       * <code>optional int32 from_x = 5;</code>
       */
      public boolean hasFromX() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 from_x = 5;</code>
       */
      public int getFromX() {
        return fromX_;
      }
      /**
       * <code>optional int32 from_x = 5;</code>
       */
      public Builder setFromX(int value) {
        bitField0_ |= 0x00000010;
        fromX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 from_x = 5;</code>
       */
      public Builder clearFromX() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fromX_ = 0;
        onChanged();
        return this;
      }

      private int fromY_ ;
      /**
       * <code>optional int32 from_y = 6;</code>
       */
      public boolean hasFromY() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 from_y = 6;</code>
       */
      public int getFromY() {
        return fromY_;
      }
      /**
       * <code>optional int32 from_y = 6;</code>
       */
      public Builder setFromY(int value) {
        bitField0_ |= 0x00000020;
        fromY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 from_y = 6;</code>
       */
      public Builder clearFromY() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fromY_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:arrive)
    }

    static {
      defaultInstance = new arrive(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:arrive)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_arrive_request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_arrive_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_arrive_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_arrive_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014arrive.proto\"P\n\016arrive_request\022\021\n\tplay" +
      "er_id\030\001 \001(\r\022\017\n\007army_id\030\002 \001(\r\022\014\n\004to_x\030\003 \001" +
      "(\005\022\014\n\004to_y\030\004 \001(\005\"l\n\006arrive\022\021\n\tplayer_id\030" +
      "\001 \001(\r\022\017\n\007army_id\030\002 \001(\r\022\014\n\004code\030\003 \001(\005\022\020\n\010" +
      "interval\030\004 \001(\r\022\016\n\006from_x\030\005 \001(\005\022\016\n\006from_y" +
      "\030\006 \001(\005B\016\n\014com.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_arrive_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_arrive_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_arrive_request_descriptor,
        new java.lang.String[] { "PlayerId", "ArmyId", "ToX", "ToY", });
    internal_static_arrive_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_arrive_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_arrive_descriptor,
        new java.lang.String[] { "PlayerId", "ArmyId", "Code", "Interval", "FromX", "FromY", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
