// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: building_occupy.proto

package com.protobuf;

public final class BuildingOccupy {
  private BuildingOccupy() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface building_occupy_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:building_occupy_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 army_id = 1;</code>
     */
    boolean hasArmyId();
    /**
     * <code>required uint32 army_id = 1;</code>
     */
    int getArmyId();

    /**
     * <code>optional int32 from_x = 2;</code>
     */
    boolean hasFromX();
    /**
     * <code>optional int32 from_x = 2;</code>
     */
    int getFromX();

    /**
     * <code>optional int32 from_y = 3;</code>
     */
    boolean hasFromY();
    /**
     * <code>optional int32 from_y = 3;</code>
     */
    int getFromY();

    /**
     * <code>optional int32 to_x = 4;</code>
     */
    boolean hasToX();
    /**
     * <code>optional int32 to_x = 4;</code>
     */
    int getToX();

    /**
     * <code>optional int32 to_y = 5;</code>
     */
    boolean hasToY();
    /**
     * <code>optional int32 to_y = 5;</code>
     */
    int getToY();
  }
  /**
   * Protobuf type {@code building_occupy_request}
   */
  public static final class building_occupy_request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:building_occupy_request)
      building_occupy_requestOrBuilder {
    // Use building_occupy_request.newBuilder() to construct.
    private building_occupy_request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private building_occupy_request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final building_occupy_request defaultInstance;
    public static building_occupy_request getDefaultInstance() {
      return defaultInstance;
    }

    public building_occupy_request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private building_occupy_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              armyId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fromX_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              fromY_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              toX_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              toY_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.BuildingOccupy.internal_static_building_occupy_request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.BuildingOccupy.internal_static_building_occupy_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.BuildingOccupy.building_occupy_request.class, com.protobuf.BuildingOccupy.building_occupy_request.Builder.class);
    }

    public static com.google.protobuf.Parser<building_occupy_request> PARSER =
        new com.google.protobuf.AbstractParser<building_occupy_request>() {
      public building_occupy_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new building_occupy_request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<building_occupy_request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ARMY_ID_FIELD_NUMBER = 1;
    private int armyId_;
    /**
     * <code>required uint32 army_id = 1;</code>
     */
    public boolean hasArmyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 army_id = 1;</code>
     */
    public int getArmyId() {
      return armyId_;
    }

    public static final int FROM_X_FIELD_NUMBER = 2;
    private int fromX_;
    /**
     * <code>optional int32 from_x = 2;</code>
     */
    public boolean hasFromX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 from_x = 2;</code>
     */
    public int getFromX() {
      return fromX_;
    }

    public static final int FROM_Y_FIELD_NUMBER = 3;
    private int fromY_;
    /**
     * <code>optional int32 from_y = 3;</code>
     */
    public boolean hasFromY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 from_y = 3;</code>
     */
    public int getFromY() {
      return fromY_;
    }

    public static final int TO_X_FIELD_NUMBER = 4;
    private int toX_;
    /**
     * <code>optional int32 to_x = 4;</code>
     */
    public boolean hasToX() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 to_x = 4;</code>
     */
    public int getToX() {
      return toX_;
    }

    public static final int TO_Y_FIELD_NUMBER = 5;
    private int toY_;
    /**
     * <code>optional int32 to_y = 5;</code>
     */
    public boolean hasToY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 to_y = 5;</code>
     */
    public int getToY() {
      return toY_;
    }

    private void initFields() {
      armyId_ = 0;
      fromX_ = 0;
      fromY_ = 0;
      toX_ = 0;
      toY_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasArmyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, armyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, fromX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, fromY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, toX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, toY_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, armyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, fromX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, fromY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, toX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, toY_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.BuildingOccupy.building_occupy_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.BuildingOccupy.building_occupy_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.BuildingOccupy.building_occupy_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.BuildingOccupy.building_occupy_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.BuildingOccupy.building_occupy_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.BuildingOccupy.building_occupy_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.BuildingOccupy.building_occupy_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.BuildingOccupy.building_occupy_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.BuildingOccupy.building_occupy_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.BuildingOccupy.building_occupy_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.BuildingOccupy.building_occupy_request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code building_occupy_request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:building_occupy_request)
        com.protobuf.BuildingOccupy.building_occupy_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.BuildingOccupy.internal_static_building_occupy_request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.BuildingOccupy.internal_static_building_occupy_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.BuildingOccupy.building_occupy_request.class, com.protobuf.BuildingOccupy.building_occupy_request.Builder.class);
      }

      // Construct using com.protobuf.BuildingOccupy.building_occupy_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        armyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fromX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        fromY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        toX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        toY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.BuildingOccupy.internal_static_building_occupy_request_descriptor;
      }

      public com.protobuf.BuildingOccupy.building_occupy_request getDefaultInstanceForType() {
        return com.protobuf.BuildingOccupy.building_occupy_request.getDefaultInstance();
      }

      public com.protobuf.BuildingOccupy.building_occupy_request build() {
        com.protobuf.BuildingOccupy.building_occupy_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.BuildingOccupy.building_occupy_request buildPartial() {
        com.protobuf.BuildingOccupy.building_occupy_request result = new com.protobuf.BuildingOccupy.building_occupy_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.armyId_ = armyId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromX_ = fromX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fromY_ = fromY_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toX_ = toX_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.toY_ = toY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.BuildingOccupy.building_occupy_request) {
          return mergeFrom((com.protobuf.BuildingOccupy.building_occupy_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.BuildingOccupy.building_occupy_request other) {
        if (other == com.protobuf.BuildingOccupy.building_occupy_request.getDefaultInstance()) return this;
        if (other.hasArmyId()) {
          setArmyId(other.getArmyId());
        }
        if (other.hasFromX()) {
          setFromX(other.getFromX());
        }
        if (other.hasFromY()) {
          setFromY(other.getFromY());
        }
        if (other.hasToX()) {
          setToX(other.getToX());
        }
        if (other.hasToY()) {
          setToY(other.getToY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasArmyId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.BuildingOccupy.building_occupy_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.BuildingOccupy.building_occupy_request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int armyId_ ;
      /**
       * <code>required uint32 army_id = 1;</code>
       */
      public boolean hasArmyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 army_id = 1;</code>
       */
      public int getArmyId() {
        return armyId_;
      }
      /**
       * <code>required uint32 army_id = 1;</code>
       */
      public Builder setArmyId(int value) {
        bitField0_ |= 0x00000001;
        armyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 army_id = 1;</code>
       */
      public Builder clearArmyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        armyId_ = 0;
        onChanged();
        return this;
      }

      private int fromX_ ;
      /**
       * <code>optional int32 from_x = 2;</code>
       */
      public boolean hasFromX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 from_x = 2;</code>
       */
      public int getFromX() {
        return fromX_;
      }
      /**
       * <code>optional int32 from_x = 2;</code>
       */
      public Builder setFromX(int value) {
        bitField0_ |= 0x00000002;
        fromX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 from_x = 2;</code>
       */
      public Builder clearFromX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromX_ = 0;
        onChanged();
        return this;
      }

      private int fromY_ ;
      /**
       * <code>optional int32 from_y = 3;</code>
       */
      public boolean hasFromY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 from_y = 3;</code>
       */
      public int getFromY() {
        return fromY_;
      }
      /**
       * <code>optional int32 from_y = 3;</code>
       */
      public Builder setFromY(int value) {
        bitField0_ |= 0x00000004;
        fromY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 from_y = 3;</code>
       */
      public Builder clearFromY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromY_ = 0;
        onChanged();
        return this;
      }

      private int toX_ ;
      /**
       * <code>optional int32 to_x = 4;</code>
       */
      public boolean hasToX() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 to_x = 4;</code>
       */
      public int getToX() {
        return toX_;
      }
      /**
       * <code>optional int32 to_x = 4;</code>
       */
      public Builder setToX(int value) {
        bitField0_ |= 0x00000008;
        toX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 to_x = 4;</code>
       */
      public Builder clearToX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toX_ = 0;
        onChanged();
        return this;
      }

      private int toY_ ;
      /**
       * <code>optional int32 to_y = 5;</code>
       */
      public boolean hasToY() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 to_y = 5;</code>
       */
      public int getToY() {
        return toY_;
      }
      /**
       * <code>optional int32 to_y = 5;</code>
       */
      public Builder setToY(int value) {
        bitField0_ |= 0x00000010;
        toY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 to_y = 5;</code>
       */
      public Builder clearToY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        toY_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:building_occupy_request)
    }

    static {
      defaultInstance = new building_occupy_request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:building_occupy_request)
  }

  public interface building_occupyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:building_occupy)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>required uint32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>optional int32 x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>optional int32 x = 2;</code>
     */
    int getX();

    /**
     * <code>optional int32 y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>optional int32 y = 3;</code>
     */
    int getY();

    /**
     * <code>optional uint32 owner_id = 4;</code>
     */
    boolean hasOwnerId();
    /**
     * <code>optional uint32 owner_id = 4;</code>
     */
    int getOwnerId();

    /**
     * <code>required uint32 player_id = 5;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required uint32 player_id = 5;</code>
     */
    int getPlayerId();

    /**
     * <code>required uint32 army_id = 6;</code>
     */
    boolean hasArmyId();
    /**
     * <code>required uint32 army_id = 6;</code>
     */
    int getArmyId();
  }
  /**
   * Protobuf type {@code building_occupy}
   */
  public static final class building_occupy extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:building_occupy)
      building_occupyOrBuilder {
    // Use building_occupy.newBuilder() to construct.
    private building_occupy(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private building_occupy(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final building_occupy defaultInstance;
    public static building_occupy getDefaultInstance() {
      return defaultInstance;
    }

    public building_occupy getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private building_occupy(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              x_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              y_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ownerId_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              playerId_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              armyId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.BuildingOccupy.internal_static_building_occupy_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.BuildingOccupy.internal_static_building_occupy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.BuildingOccupy.building_occupy.class, com.protobuf.BuildingOccupy.building_occupy.Builder.class);
    }

    public static com.google.protobuf.Parser<building_occupy> PARSER =
        new com.google.protobuf.AbstractParser<building_occupy>() {
      public building_occupy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new building_occupy(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<building_occupy> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required uint32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private int x_;
    /**
     * <code>optional int32 x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 x = 2;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private int y_;
    /**
     * <code>optional int32 y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 y = 3;</code>
     */
    public int getY() {
      return y_;
    }

    public static final int OWNER_ID_FIELD_NUMBER = 4;
    private int ownerId_;
    /**
     * <code>optional uint32 owner_id = 4;</code>
     */
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 owner_id = 4;</code>
     */
    public int getOwnerId() {
      return ownerId_;
    }

    public static final int PLAYER_ID_FIELD_NUMBER = 5;
    private int playerId_;
    /**
     * <code>required uint32 player_id = 5;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 player_id = 5;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int ARMY_ID_FIELD_NUMBER = 6;
    private int armyId_;
    /**
     * <code>required uint32 army_id = 6;</code>
     */
    public boolean hasArmyId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required uint32 army_id = 6;</code>
     */
    public int getArmyId() {
      return armyId_;
    }

    private void initFields() {
      code_ = 0;
      x_ = 0;
      y_ = 0;
      ownerId_ = 0;
      playerId_ = 0;
      armyId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArmyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, ownerId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, playerId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, armyId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, ownerId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, playerId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, armyId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.BuildingOccupy.building_occupy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.BuildingOccupy.building_occupy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.BuildingOccupy.building_occupy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.BuildingOccupy.building_occupy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.BuildingOccupy.building_occupy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.BuildingOccupy.building_occupy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.BuildingOccupy.building_occupy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.BuildingOccupy.building_occupy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.BuildingOccupy.building_occupy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.BuildingOccupy.building_occupy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.BuildingOccupy.building_occupy prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code building_occupy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:building_occupy)
        com.protobuf.BuildingOccupy.building_occupyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.BuildingOccupy.internal_static_building_occupy_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.BuildingOccupy.internal_static_building_occupy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.BuildingOccupy.building_occupy.class, com.protobuf.BuildingOccupy.building_occupy.Builder.class);
      }

      // Construct using com.protobuf.BuildingOccupy.building_occupy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ownerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        armyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.BuildingOccupy.internal_static_building_occupy_descriptor;
      }

      public com.protobuf.BuildingOccupy.building_occupy getDefaultInstanceForType() {
        return com.protobuf.BuildingOccupy.building_occupy.getDefaultInstance();
      }

      public com.protobuf.BuildingOccupy.building_occupy build() {
        com.protobuf.BuildingOccupy.building_occupy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.BuildingOccupy.building_occupy buildPartial() {
        com.protobuf.BuildingOccupy.building_occupy result = new com.protobuf.BuildingOccupy.building_occupy(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ownerId_ = ownerId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.armyId_ = armyId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.BuildingOccupy.building_occupy) {
          return mergeFrom((com.protobuf.BuildingOccupy.building_occupy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.BuildingOccupy.building_occupy other) {
        if (other == com.protobuf.BuildingOccupy.building_occupy.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasOwnerId()) {
          setOwnerId(other.getOwnerId());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasArmyId()) {
          setArmyId(other.getArmyId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasArmyId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.BuildingOccupy.building_occupy parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.BuildingOccupy.building_occupy) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>required uint32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required uint32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private int x_ ;
      /**
       * <code>optional int32 x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 x = 2;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 2;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional int32 y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 y = 3;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 3;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0;
        onChanged();
        return this;
      }

      private int ownerId_ ;
      /**
       * <code>optional uint32 owner_id = 4;</code>
       */
      public boolean hasOwnerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 owner_id = 4;</code>
       */
      public int getOwnerId() {
        return ownerId_;
      }
      /**
       * <code>optional uint32 owner_id = 4;</code>
       */
      public Builder setOwnerId(int value) {
        bitField0_ |= 0x00000008;
        ownerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 owner_id = 4;</code>
       */
      public Builder clearOwnerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ownerId_ = 0;
        onChanged();
        return this;
      }

      private int playerId_ ;
      /**
       * <code>required uint32 player_id = 5;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 player_id = 5;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required uint32 player_id = 5;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000010;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 player_id = 5;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        playerId_ = 0;
        onChanged();
        return this;
      }

      private int armyId_ ;
      /**
       * <code>required uint32 army_id = 6;</code>
       */
      public boolean hasArmyId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required uint32 army_id = 6;</code>
       */
      public int getArmyId() {
        return armyId_;
      }
      /**
       * <code>required uint32 army_id = 6;</code>
       */
      public Builder setArmyId(int value) {
        bitField0_ |= 0x00000020;
        armyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 army_id = 6;</code>
       */
      public Builder clearArmyId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        armyId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:building_occupy)
    }

    static {
      defaultInstance = new building_occupy(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:building_occupy)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_occupy_request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_building_occupy_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_building_occupy_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_building_occupy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025building_occupy.proto\"f\n\027building_occu" +
      "py_request\022\017\n\007army_id\030\001 \002(\r\022\016\n\006from_x\030\002 " +
      "\001(\005\022\016\n\006from_y\030\003 \001(\005\022\014\n\004to_x\030\004 \001(\005\022\014\n\004to_" +
      "y\030\005 \001(\005\"k\n\017building_occupy\022\014\n\004code\030\001 \002(\r" +
      "\022\t\n\001x\030\002 \001(\005\022\t\n\001y\030\003 \001(\005\022\020\n\010owner_id\030\004 \001(\r" +
      "\022\021\n\tplayer_id\030\005 \002(\r\022\017\n\007army_id\030\006 \002(\rB\016\n\014" +
      "com.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_building_occupy_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_building_occupy_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_building_occupy_request_descriptor,
        new java.lang.String[] { "ArmyId", "FromX", "FromY", "ToX", "ToY", });
    internal_static_building_occupy_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_building_occupy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_building_occupy_descriptor,
        new java.lang.String[] { "Code", "X", "Y", "OwnerId", "PlayerId", "ArmyId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
