// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hero_info.proto

package com.protobuf;

public final class HeroInfo {
  private HeroInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface hero_infoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hero_info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 hero_id = 1;</code>
     */
    boolean hasHeroId();
    /**
     * <code>required uint32 hero_id = 1;</code>
     */
    int getHeroId();

    /**
     * <code>required uint32 hero_type = 2;</code>
     */
    boolean hasHeroType();
    /**
     * <code>required uint32 hero_type = 2;</code>
     */
    int getHeroType();

    /**
     * <code>required uint32 hero_level = 3;</code>
     */
    boolean hasHeroLevel();
    /**
     * <code>required uint32 hero_level = 3;</code>
     */
    int getHeroLevel();

    /**
     * <code>required uint32 hero_state = 4;</code>
     */
    boolean hasHeroState();
    /**
     * <code>required uint32 hero_state = 4;</code>
     */
    int getHeroState();

    /**
     * <code>optional uint32 hero_death_time = 5;</code>
     */
    boolean hasHeroDeathTime();
    /**
     * <code>optional uint32 hero_death_time = 5;</code>
     */
    int getHeroDeathTime();

    /**
     * <code>optional uint32 energy = 6;</code>
     */
    boolean hasEnergy();
    /**
     * <code>optional uint32 energy = 6;</code>
     */
    int getEnergy();

    /**
     * <code>optional uint32 start_energy = 7;</code>
     */
    boolean hasStartEnergy();
    /**
     * <code>optional uint32 start_energy = 7;</code>
     */
    int getStartEnergy();
  }
  /**
   * Protobuf type {@code hero_info}
   */
  public static final class hero_info extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hero_info)
      hero_infoOrBuilder {
    // Use hero_info.newBuilder() to construct.
    private hero_info(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private hero_info(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final hero_info defaultInstance;
    public static hero_info getDefaultInstance() {
      return defaultInstance;
    }

    public hero_info getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private hero_info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              heroId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              heroType_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              heroLevel_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              heroState_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              heroDeathTime_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              energy_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              startEnergy_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.HeroInfo.internal_static_hero_info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.HeroInfo.internal_static_hero_info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.HeroInfo.hero_info.class, com.protobuf.HeroInfo.hero_info.Builder.class);
    }

    public static com.google.protobuf.Parser<hero_info> PARSER =
        new com.google.protobuf.AbstractParser<hero_info>() {
      public hero_info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new hero_info(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<hero_info> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HERO_ID_FIELD_NUMBER = 1;
    private int heroId_;
    /**
     * <code>required uint32 hero_id = 1;</code>
     */
    public boolean hasHeroId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 hero_id = 1;</code>
     */
    public int getHeroId() {
      return heroId_;
    }

    public static final int HERO_TYPE_FIELD_NUMBER = 2;
    private int heroType_;
    /**
     * <code>required uint32 hero_type = 2;</code>
     */
    public boolean hasHeroType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 hero_type = 2;</code>
     */
    public int getHeroType() {
      return heroType_;
    }

    public static final int HERO_LEVEL_FIELD_NUMBER = 3;
    private int heroLevel_;
    /**
     * <code>required uint32 hero_level = 3;</code>
     */
    public boolean hasHeroLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 hero_level = 3;</code>
     */
    public int getHeroLevel() {
      return heroLevel_;
    }

    public static final int HERO_STATE_FIELD_NUMBER = 4;
    private int heroState_;
    /**
     * <code>required uint32 hero_state = 4;</code>
     */
    public boolean hasHeroState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 hero_state = 4;</code>
     */
    public int getHeroState() {
      return heroState_;
    }

    public static final int HERO_DEATH_TIME_FIELD_NUMBER = 5;
    private int heroDeathTime_;
    /**
     * <code>optional uint32 hero_death_time = 5;</code>
     */
    public boolean hasHeroDeathTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 hero_death_time = 5;</code>
     */
    public int getHeroDeathTime() {
      return heroDeathTime_;
    }

    public static final int ENERGY_FIELD_NUMBER = 6;
    private int energy_;
    /**
     * <code>optional uint32 energy = 6;</code>
     */
    public boolean hasEnergy() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 energy = 6;</code>
     */
    public int getEnergy() {
      return energy_;
    }

    public static final int START_ENERGY_FIELD_NUMBER = 7;
    private int startEnergy_;
    /**
     * <code>optional uint32 start_energy = 7;</code>
     */
    public boolean hasStartEnergy() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 start_energy = 7;</code>
     */
    public int getStartEnergy() {
      return startEnergy_;
    }

    private void initFields() {
      heroId_ = 0;
      heroType_ = 0;
      heroLevel_ = 0;
      heroState_ = 0;
      heroDeathTime_ = 0;
      energy_ = 0;
      startEnergy_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeroId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeroType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeroLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeroState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, heroId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, heroType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, heroLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, heroState_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, heroDeathTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, energy_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, startEnergy_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, heroId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, heroType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, heroLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, heroState_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, heroDeathTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, energy_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, startEnergy_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.HeroInfo.hero_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.HeroInfo.hero_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.HeroInfo.hero_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.HeroInfo.hero_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.HeroInfo.hero_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.HeroInfo.hero_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.HeroInfo.hero_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.HeroInfo.hero_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.HeroInfo.hero_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.HeroInfo.hero_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.HeroInfo.hero_info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hero_info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hero_info)
        com.protobuf.HeroInfo.hero_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.HeroInfo.internal_static_hero_info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.HeroInfo.internal_static_hero_info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.HeroInfo.hero_info.class, com.protobuf.HeroInfo.hero_info.Builder.class);
      }

      // Construct using com.protobuf.HeroInfo.hero_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        heroId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        heroType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        heroLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        heroState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        heroDeathTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        energy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        startEnergy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.HeroInfo.internal_static_hero_info_descriptor;
      }

      public com.protobuf.HeroInfo.hero_info getDefaultInstanceForType() {
        return com.protobuf.HeroInfo.hero_info.getDefaultInstance();
      }

      public com.protobuf.HeroInfo.hero_info build() {
        com.protobuf.HeroInfo.hero_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.HeroInfo.hero_info buildPartial() {
        com.protobuf.HeroInfo.hero_info result = new com.protobuf.HeroInfo.hero_info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.heroId_ = heroId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.heroType_ = heroType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.heroLevel_ = heroLevel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.heroState_ = heroState_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.heroDeathTime_ = heroDeathTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.energy_ = energy_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.startEnergy_ = startEnergy_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.HeroInfo.hero_info) {
          return mergeFrom((com.protobuf.HeroInfo.hero_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.HeroInfo.hero_info other) {
        if (other == com.protobuf.HeroInfo.hero_info.getDefaultInstance()) return this;
        if (other.hasHeroId()) {
          setHeroId(other.getHeroId());
        }
        if (other.hasHeroType()) {
          setHeroType(other.getHeroType());
        }
        if (other.hasHeroLevel()) {
          setHeroLevel(other.getHeroLevel());
        }
        if (other.hasHeroState()) {
          setHeroState(other.getHeroState());
        }
        if (other.hasHeroDeathTime()) {
          setHeroDeathTime(other.getHeroDeathTime());
        }
        if (other.hasEnergy()) {
          setEnergy(other.getEnergy());
        }
        if (other.hasStartEnergy()) {
          setStartEnergy(other.getStartEnergy());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeroId()) {
          
          return false;
        }
        if (!hasHeroType()) {
          
          return false;
        }
        if (!hasHeroLevel()) {
          
          return false;
        }
        if (!hasHeroState()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.HeroInfo.hero_info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.HeroInfo.hero_info) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int heroId_ ;
      /**
       * <code>required uint32 hero_id = 1;</code>
       */
      public boolean hasHeroId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 hero_id = 1;</code>
       */
      public int getHeroId() {
        return heroId_;
      }
      /**
       * <code>required uint32 hero_id = 1;</code>
       */
      public Builder setHeroId(int value) {
        bitField0_ |= 0x00000001;
        heroId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 hero_id = 1;</code>
       */
      public Builder clearHeroId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        heroId_ = 0;
        onChanged();
        return this;
      }

      private int heroType_ ;
      /**
       * <code>required uint32 hero_type = 2;</code>
       */
      public boolean hasHeroType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 hero_type = 2;</code>
       */
      public int getHeroType() {
        return heroType_;
      }
      /**
       * <code>required uint32 hero_type = 2;</code>
       */
      public Builder setHeroType(int value) {
        bitField0_ |= 0x00000002;
        heroType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 hero_type = 2;</code>
       */
      public Builder clearHeroType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        heroType_ = 0;
        onChanged();
        return this;
      }

      private int heroLevel_ ;
      /**
       * <code>required uint32 hero_level = 3;</code>
       */
      public boolean hasHeroLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 hero_level = 3;</code>
       */
      public int getHeroLevel() {
        return heroLevel_;
      }
      /**
       * <code>required uint32 hero_level = 3;</code>
       */
      public Builder setHeroLevel(int value) {
        bitField0_ |= 0x00000004;
        heroLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 hero_level = 3;</code>
       */
      public Builder clearHeroLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        heroLevel_ = 0;
        onChanged();
        return this;
      }

      private int heroState_ ;
      /**
       * <code>required uint32 hero_state = 4;</code>
       */
      public boolean hasHeroState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 hero_state = 4;</code>
       */
      public int getHeroState() {
        return heroState_;
      }
      /**
       * <code>required uint32 hero_state = 4;</code>
       */
      public Builder setHeroState(int value) {
        bitField0_ |= 0x00000008;
        heroState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 hero_state = 4;</code>
       */
      public Builder clearHeroState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        heroState_ = 0;
        onChanged();
        return this;
      }

      private int heroDeathTime_ ;
      /**
       * <code>optional uint32 hero_death_time = 5;</code>
       */
      public boolean hasHeroDeathTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 hero_death_time = 5;</code>
       */
      public int getHeroDeathTime() {
        return heroDeathTime_;
      }
      /**
       * <code>optional uint32 hero_death_time = 5;</code>
       */
      public Builder setHeroDeathTime(int value) {
        bitField0_ |= 0x00000010;
        heroDeathTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 hero_death_time = 5;</code>
       */
      public Builder clearHeroDeathTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        heroDeathTime_ = 0;
        onChanged();
        return this;
      }

      private int energy_ ;
      /**
       * <code>optional uint32 energy = 6;</code>
       */
      public boolean hasEnergy() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 energy = 6;</code>
       */
      public int getEnergy() {
        return energy_;
      }
      /**
       * <code>optional uint32 energy = 6;</code>
       */
      public Builder setEnergy(int value) {
        bitField0_ |= 0x00000020;
        energy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 energy = 6;</code>
       */
      public Builder clearEnergy() {
        bitField0_ = (bitField0_ & ~0x00000020);
        energy_ = 0;
        onChanged();
        return this;
      }

      private int startEnergy_ ;
      /**
       * <code>optional uint32 start_energy = 7;</code>
       */
      public boolean hasStartEnergy() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 start_energy = 7;</code>
       */
      public int getStartEnergy() {
        return startEnergy_;
      }
      /**
       * <code>optional uint32 start_energy = 7;</code>
       */
      public Builder setStartEnergy(int value) {
        bitField0_ |= 0x00000040;
        startEnergy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 start_energy = 7;</code>
       */
      public Builder clearStartEnergy() {
        bitField0_ = (bitField0_ & ~0x00000040);
        startEnergy_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hero_info)
    }

    static {
      defaultInstance = new hero_info(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hero_info)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hero_info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hero_info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017hero_info.proto\"\226\001\n\thero_info\022\017\n\007hero_" +
      "id\030\001 \002(\r\022\021\n\thero_type\030\002 \002(\r\022\022\n\nhero_leve" +
      "l\030\003 \002(\r\022\022\n\nhero_state\030\004 \002(\r\022\027\n\017hero_deat" +
      "h_time\030\005 \001(\r\022\016\n\006energy\030\006 \001(\r\022\024\n\014start_en" +
      "ergy\030\007 \001(\rB\016\n\014com.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hero_info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hero_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hero_info_descriptor,
        new java.lang.String[] { "HeroId", "HeroType", "HeroLevel", "HeroState", "HeroDeathTime", "Energy", "StartEnergy", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
