// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_create_hero.proto

package com.protobuf;

public final class TestCreateHero {
  private TestCreateHero() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface test_create_hero_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test_create_hero_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 hero_type = 1;</code>
     */
    boolean hasHeroType();
    /**
     * <code>required uint32 hero_type = 1;</code>
     */
    int getHeroType();
  }
  /**
   * Protobuf type {@code test_create_hero_request}
   */
  public static final class test_create_hero_request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:test_create_hero_request)
      test_create_hero_requestOrBuilder {
    // Use test_create_hero_request.newBuilder() to construct.
    private test_create_hero_request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private test_create_hero_request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final test_create_hero_request defaultInstance;
    public static test_create_hero_request getDefaultInstance() {
      return defaultInstance;
    }

    public test_create_hero_request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private test_create_hero_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              heroType_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.TestCreateHero.internal_static_test_create_hero_request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.TestCreateHero.internal_static_test_create_hero_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.TestCreateHero.test_create_hero_request.class, com.protobuf.TestCreateHero.test_create_hero_request.Builder.class);
    }

    public static com.google.protobuf.Parser<test_create_hero_request> PARSER =
        new com.google.protobuf.AbstractParser<test_create_hero_request>() {
      public test_create_hero_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new test_create_hero_request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<test_create_hero_request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HERO_TYPE_FIELD_NUMBER = 1;
    private int heroType_;
    /**
     * <code>required uint32 hero_type = 1;</code>
     */
    public boolean hasHeroType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 hero_type = 1;</code>
     */
    public int getHeroType() {
      return heroType_;
    }

    private void initFields() {
      heroType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeroType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, heroType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, heroType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.TestCreateHero.test_create_hero_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateHero.test_create_hero_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateHero.test_create_hero_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateHero.test_create_hero_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateHero.test_create_hero_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateHero.test_create_hero_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateHero.test_create_hero_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.TestCreateHero.test_create_hero_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateHero.test_create_hero_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateHero.test_create_hero_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.TestCreateHero.test_create_hero_request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test_create_hero_request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test_create_hero_request)
        com.protobuf.TestCreateHero.test_create_hero_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.TestCreateHero.internal_static_test_create_hero_request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.TestCreateHero.internal_static_test_create_hero_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.TestCreateHero.test_create_hero_request.class, com.protobuf.TestCreateHero.test_create_hero_request.Builder.class);
      }

      // Construct using com.protobuf.TestCreateHero.test_create_hero_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        heroType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.TestCreateHero.internal_static_test_create_hero_request_descriptor;
      }

      public com.protobuf.TestCreateHero.test_create_hero_request getDefaultInstanceForType() {
        return com.protobuf.TestCreateHero.test_create_hero_request.getDefaultInstance();
      }

      public com.protobuf.TestCreateHero.test_create_hero_request build() {
        com.protobuf.TestCreateHero.test_create_hero_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.TestCreateHero.test_create_hero_request buildPartial() {
        com.protobuf.TestCreateHero.test_create_hero_request result = new com.protobuf.TestCreateHero.test_create_hero_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.heroType_ = heroType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.TestCreateHero.test_create_hero_request) {
          return mergeFrom((com.protobuf.TestCreateHero.test_create_hero_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.TestCreateHero.test_create_hero_request other) {
        if (other == com.protobuf.TestCreateHero.test_create_hero_request.getDefaultInstance()) return this;
        if (other.hasHeroType()) {
          setHeroType(other.getHeroType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeroType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.TestCreateHero.test_create_hero_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.TestCreateHero.test_create_hero_request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int heroType_ ;
      /**
       * <code>required uint32 hero_type = 1;</code>
       */
      public boolean hasHeroType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 hero_type = 1;</code>
       */
      public int getHeroType() {
        return heroType_;
      }
      /**
       * <code>required uint32 hero_type = 1;</code>
       */
      public Builder setHeroType(int value) {
        bitField0_ |= 0x00000001;
        heroType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 hero_type = 1;</code>
       */
      public Builder clearHeroType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        heroType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test_create_hero_request)
    }

    static {
      defaultInstance = new test_create_hero_request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test_create_hero_request)
  }

  public interface test_create_heroOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test_create_hero)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 player_id = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required uint32 player_id = 1;</code>
     */
    int getPlayerId();

    /**
     * <code>repeated .hero_info heros = 2;</code>
     */
    java.util.List<com.protobuf.HeroInfo.hero_info> 
        getHerosList();
    /**
     * <code>repeated .hero_info heros = 2;</code>
     */
    com.protobuf.HeroInfo.hero_info getHeros(int index);
    /**
     * <code>repeated .hero_info heros = 2;</code>
     */
    int getHerosCount();
    /**
     * <code>repeated .hero_info heros = 2;</code>
     */
    java.util.List<? extends com.protobuf.HeroInfo.hero_infoOrBuilder> 
        getHerosOrBuilderList();
    /**
     * <code>repeated .hero_info heros = 2;</code>
     */
    com.protobuf.HeroInfo.hero_infoOrBuilder getHerosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code test_create_hero}
   */
  public static final class test_create_hero extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:test_create_hero)
      test_create_heroOrBuilder {
    // Use test_create_hero.newBuilder() to construct.
    private test_create_hero(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private test_create_hero(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final test_create_hero defaultInstance;
    public static test_create_hero getDefaultInstance() {
      return defaultInstance;
    }

    public test_create_hero getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private test_create_hero(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readUInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                heros_ = new java.util.ArrayList<com.protobuf.HeroInfo.hero_info>();
                mutable_bitField0_ |= 0x00000002;
              }
              heros_.add(input.readMessage(com.protobuf.HeroInfo.hero_info.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          heros_ = java.util.Collections.unmodifiableList(heros_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.TestCreateHero.internal_static_test_create_hero_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.TestCreateHero.internal_static_test_create_hero_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.TestCreateHero.test_create_hero.class, com.protobuf.TestCreateHero.test_create_hero.Builder.class);
    }

    public static com.google.protobuf.Parser<test_create_hero> PARSER =
        new com.google.protobuf.AbstractParser<test_create_hero>() {
      public test_create_hero parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new test_create_hero(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<test_create_hero> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>required uint32 player_id = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 player_id = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int HEROS_FIELD_NUMBER = 2;
    private java.util.List<com.protobuf.HeroInfo.hero_info> heros_;
    /**
     * <code>repeated .hero_info heros = 2;</code>
     */
    public java.util.List<com.protobuf.HeroInfo.hero_info> getHerosList() {
      return heros_;
    }
    /**
     * <code>repeated .hero_info heros = 2;</code>
     */
    public java.util.List<? extends com.protobuf.HeroInfo.hero_infoOrBuilder> 
        getHerosOrBuilderList() {
      return heros_;
    }
    /**
     * <code>repeated .hero_info heros = 2;</code>
     */
    public int getHerosCount() {
      return heros_.size();
    }
    /**
     * <code>repeated .hero_info heros = 2;</code>
     */
    public com.protobuf.HeroInfo.hero_info getHeros(int index) {
      return heros_.get(index);
    }
    /**
     * <code>repeated .hero_info heros = 2;</code>
     */
    public com.protobuf.HeroInfo.hero_infoOrBuilder getHerosOrBuilder(
        int index) {
      return heros_.get(index);
    }

    private void initFields() {
      playerId_ = 0;
      heros_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getHerosCount(); i++) {
        if (!getHeros(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, playerId_);
      }
      for (int i = 0; i < heros_.size(); i++) {
        output.writeMessage(2, heros_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, playerId_);
      }
      for (int i = 0; i < heros_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, heros_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.TestCreateHero.test_create_hero parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateHero.test_create_hero parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateHero.test_create_hero parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateHero.test_create_hero parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateHero.test_create_hero parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateHero.test_create_hero parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateHero.test_create_hero parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.TestCreateHero.test_create_hero parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateHero.test_create_hero parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateHero.test_create_hero parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.TestCreateHero.test_create_hero prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test_create_hero}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test_create_hero)
        com.protobuf.TestCreateHero.test_create_heroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.TestCreateHero.internal_static_test_create_hero_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.TestCreateHero.internal_static_test_create_hero_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.TestCreateHero.test_create_hero.class, com.protobuf.TestCreateHero.test_create_hero.Builder.class);
      }

      // Construct using com.protobuf.TestCreateHero.test_create_hero.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHerosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (herosBuilder_ == null) {
          heros_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          herosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.TestCreateHero.internal_static_test_create_hero_descriptor;
      }

      public com.protobuf.TestCreateHero.test_create_hero getDefaultInstanceForType() {
        return com.protobuf.TestCreateHero.test_create_hero.getDefaultInstance();
      }

      public com.protobuf.TestCreateHero.test_create_hero build() {
        com.protobuf.TestCreateHero.test_create_hero result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.TestCreateHero.test_create_hero buildPartial() {
        com.protobuf.TestCreateHero.test_create_hero result = new com.protobuf.TestCreateHero.test_create_hero(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (herosBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            heros_ = java.util.Collections.unmodifiableList(heros_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.heros_ = heros_;
        } else {
          result.heros_ = herosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.TestCreateHero.test_create_hero) {
          return mergeFrom((com.protobuf.TestCreateHero.test_create_hero)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.TestCreateHero.test_create_hero other) {
        if (other == com.protobuf.TestCreateHero.test_create_hero.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (herosBuilder_ == null) {
          if (!other.heros_.isEmpty()) {
            if (heros_.isEmpty()) {
              heros_ = other.heros_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureHerosIsMutable();
              heros_.addAll(other.heros_);
            }
            onChanged();
          }
        } else {
          if (!other.heros_.isEmpty()) {
            if (herosBuilder_.isEmpty()) {
              herosBuilder_.dispose();
              herosBuilder_ = null;
              heros_ = other.heros_;
              bitField0_ = (bitField0_ & ~0x00000002);
              herosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHerosFieldBuilder() : null;
            } else {
              herosBuilder_.addAllMessages(other.heros_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        for (int i = 0; i < getHerosCount(); i++) {
          if (!getHeros(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.TestCreateHero.test_create_hero parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.TestCreateHero.test_create_hero) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int playerId_ ;
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.protobuf.HeroInfo.hero_info> heros_ =
        java.util.Collections.emptyList();
      private void ensureHerosIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          heros_ = new java.util.ArrayList<com.protobuf.HeroInfo.hero_info>(heros_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.protobuf.HeroInfo.hero_info, com.protobuf.HeroInfo.hero_info.Builder, com.protobuf.HeroInfo.hero_infoOrBuilder> herosBuilder_;

      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public java.util.List<com.protobuf.HeroInfo.hero_info> getHerosList() {
        if (herosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(heros_);
        } else {
          return herosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public int getHerosCount() {
        if (herosBuilder_ == null) {
          return heros_.size();
        } else {
          return herosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public com.protobuf.HeroInfo.hero_info getHeros(int index) {
        if (herosBuilder_ == null) {
          return heros_.get(index);
        } else {
          return herosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public Builder setHeros(
          int index, com.protobuf.HeroInfo.hero_info value) {
        if (herosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHerosIsMutable();
          heros_.set(index, value);
          onChanged();
        } else {
          herosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public Builder setHeros(
          int index, com.protobuf.HeroInfo.hero_info.Builder builderForValue) {
        if (herosBuilder_ == null) {
          ensureHerosIsMutable();
          heros_.set(index, builderForValue.build());
          onChanged();
        } else {
          herosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public Builder addHeros(com.protobuf.HeroInfo.hero_info value) {
        if (herosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHerosIsMutable();
          heros_.add(value);
          onChanged();
        } else {
          herosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public Builder addHeros(
          int index, com.protobuf.HeroInfo.hero_info value) {
        if (herosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHerosIsMutable();
          heros_.add(index, value);
          onChanged();
        } else {
          herosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public Builder addHeros(
          com.protobuf.HeroInfo.hero_info.Builder builderForValue) {
        if (herosBuilder_ == null) {
          ensureHerosIsMutable();
          heros_.add(builderForValue.build());
          onChanged();
        } else {
          herosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public Builder addHeros(
          int index, com.protobuf.HeroInfo.hero_info.Builder builderForValue) {
        if (herosBuilder_ == null) {
          ensureHerosIsMutable();
          heros_.add(index, builderForValue.build());
          onChanged();
        } else {
          herosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public Builder addAllHeros(
          java.lang.Iterable<? extends com.protobuf.HeroInfo.hero_info> values) {
        if (herosBuilder_ == null) {
          ensureHerosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, heros_);
          onChanged();
        } else {
          herosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public Builder clearHeros() {
        if (herosBuilder_ == null) {
          heros_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          herosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public Builder removeHeros(int index) {
        if (herosBuilder_ == null) {
          ensureHerosIsMutable();
          heros_.remove(index);
          onChanged();
        } else {
          herosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public com.protobuf.HeroInfo.hero_info.Builder getHerosBuilder(
          int index) {
        return getHerosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public com.protobuf.HeroInfo.hero_infoOrBuilder getHerosOrBuilder(
          int index) {
        if (herosBuilder_ == null) {
          return heros_.get(index);  } else {
          return herosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public java.util.List<? extends com.protobuf.HeroInfo.hero_infoOrBuilder> 
           getHerosOrBuilderList() {
        if (herosBuilder_ != null) {
          return herosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(heros_);
        }
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public com.protobuf.HeroInfo.hero_info.Builder addHerosBuilder() {
        return getHerosFieldBuilder().addBuilder(
            com.protobuf.HeroInfo.hero_info.getDefaultInstance());
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public com.protobuf.HeroInfo.hero_info.Builder addHerosBuilder(
          int index) {
        return getHerosFieldBuilder().addBuilder(
            index, com.protobuf.HeroInfo.hero_info.getDefaultInstance());
      }
      /**
       * <code>repeated .hero_info heros = 2;</code>
       */
      public java.util.List<com.protobuf.HeroInfo.hero_info.Builder> 
           getHerosBuilderList() {
        return getHerosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.protobuf.HeroInfo.hero_info, com.protobuf.HeroInfo.hero_info.Builder, com.protobuf.HeroInfo.hero_infoOrBuilder> 
          getHerosFieldBuilder() {
        if (herosBuilder_ == null) {
          herosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.protobuf.HeroInfo.hero_info, com.protobuf.HeroInfo.hero_info.Builder, com.protobuf.HeroInfo.hero_infoOrBuilder>(
                  heros_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          heros_ = null;
        }
        return herosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:test_create_hero)
    }

    static {
      defaultInstance = new test_create_hero(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test_create_hero)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_create_hero_request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_create_hero_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_create_hero_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_create_hero_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026test_create_hero.proto\032\017hero_info.prot" +
      "o\"-\n\030test_create_hero_request\022\021\n\thero_ty" +
      "pe\030\001 \002(\r\"@\n\020test_create_hero\022\021\n\tplayer_i" +
      "d\030\001 \002(\r\022\031\n\005heros\030\002 \003(\0132\n.hero_infoB\016\n\014co" +
      "m.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protobuf.HeroInfo.getDescriptor(),
        }, assigner);
    internal_static_test_create_hero_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_create_hero_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_create_hero_request_descriptor,
        new java.lang.String[] { "HeroType", });
    internal_static_test_create_hero_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_create_hero_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_create_hero_descriptor,
        new java.lang.String[] { "PlayerId", "Heros", });
    com.protobuf.HeroInfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
