// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_create_item.proto

package com.protobuf;

public final class TestCreateItem {
  private TestCreateItem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface test_create_item_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test_create_item_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 item_type = 1;</code>
     */
    boolean hasItemType();
    /**
     * <code>required uint32 item_type = 1;</code>
     */
    int getItemType();
  }
  /**
   * Protobuf type {@code test_create_item_request}
   */
  public static final class test_create_item_request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:test_create_item_request)
      test_create_item_requestOrBuilder {
    // Use test_create_item_request.newBuilder() to construct.
    private test_create_item_request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private test_create_item_request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final test_create_item_request defaultInstance;
    public static test_create_item_request getDefaultInstance() {
      return defaultInstance;
    }

    public test_create_item_request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private test_create_item_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              itemType_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.TestCreateItem.internal_static_test_create_item_request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.TestCreateItem.internal_static_test_create_item_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.TestCreateItem.test_create_item_request.class, com.protobuf.TestCreateItem.test_create_item_request.Builder.class);
    }

    public static com.google.protobuf.Parser<test_create_item_request> PARSER =
        new com.google.protobuf.AbstractParser<test_create_item_request>() {
      public test_create_item_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new test_create_item_request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<test_create_item_request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ITEM_TYPE_FIELD_NUMBER = 1;
    private int itemType_;
    /**
     * <code>required uint32 item_type = 1;</code>
     */
    public boolean hasItemType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 item_type = 1;</code>
     */
    public int getItemType() {
      return itemType_;
    }

    private void initFields() {
      itemType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasItemType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, itemType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, itemType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.TestCreateItem.test_create_item_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateItem.test_create_item_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateItem.test_create_item_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateItem.test_create_item_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateItem.test_create_item_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateItem.test_create_item_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateItem.test_create_item_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.TestCreateItem.test_create_item_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateItem.test_create_item_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateItem.test_create_item_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.TestCreateItem.test_create_item_request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test_create_item_request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test_create_item_request)
        com.protobuf.TestCreateItem.test_create_item_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.TestCreateItem.internal_static_test_create_item_request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.TestCreateItem.internal_static_test_create_item_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.TestCreateItem.test_create_item_request.class, com.protobuf.TestCreateItem.test_create_item_request.Builder.class);
      }

      // Construct using com.protobuf.TestCreateItem.test_create_item_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        itemType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.TestCreateItem.internal_static_test_create_item_request_descriptor;
      }

      public com.protobuf.TestCreateItem.test_create_item_request getDefaultInstanceForType() {
        return com.protobuf.TestCreateItem.test_create_item_request.getDefaultInstance();
      }

      public com.protobuf.TestCreateItem.test_create_item_request build() {
        com.protobuf.TestCreateItem.test_create_item_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.TestCreateItem.test_create_item_request buildPartial() {
        com.protobuf.TestCreateItem.test_create_item_request result = new com.protobuf.TestCreateItem.test_create_item_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemType_ = itemType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.TestCreateItem.test_create_item_request) {
          return mergeFrom((com.protobuf.TestCreateItem.test_create_item_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.TestCreateItem.test_create_item_request other) {
        if (other == com.protobuf.TestCreateItem.test_create_item_request.getDefaultInstance()) return this;
        if (other.hasItemType()) {
          setItemType(other.getItemType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasItemType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.TestCreateItem.test_create_item_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.TestCreateItem.test_create_item_request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int itemType_ ;
      /**
       * <code>required uint32 item_type = 1;</code>
       */
      public boolean hasItemType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 item_type = 1;</code>
       */
      public int getItemType() {
        return itemType_;
      }
      /**
       * <code>required uint32 item_type = 1;</code>
       */
      public Builder setItemType(int value) {
        bitField0_ |= 0x00000001;
        itemType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 item_type = 1;</code>
       */
      public Builder clearItemType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test_create_item_request)
    }

    static {
      defaultInstance = new test_create_item_request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test_create_item_request)
  }

  public interface test_create_itemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test_create_item)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 player_id = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required uint32 player_id = 1;</code>
     */
    int getPlayerId();

    /**
     * <code>repeated .test_create_item.Item items = 2;</code>
     */
    java.util.List<com.protobuf.TestCreateItem.test_create_item.Item> 
        getItemsList();
    /**
     * <code>repeated .test_create_item.Item items = 2;</code>
     */
    com.protobuf.TestCreateItem.test_create_item.Item getItems(int index);
    /**
     * <code>repeated .test_create_item.Item items = 2;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .test_create_item.Item items = 2;</code>
     */
    java.util.List<? extends com.protobuf.TestCreateItem.test_create_item.ItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .test_create_item.Item items = 2;</code>
     */
    com.protobuf.TestCreateItem.test_create_item.ItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code test_create_item}
   */
  public static final class test_create_item extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:test_create_item)
      test_create_itemOrBuilder {
    // Use test_create_item.newBuilder() to construct.
    private test_create_item(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private test_create_item(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final test_create_item defaultInstance;
    public static test_create_item getDefaultInstance() {
      return defaultInstance;
    }

    public test_create_item getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private test_create_item(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readUInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                items_ = new java.util.ArrayList<com.protobuf.TestCreateItem.test_create_item.Item>();
                mutable_bitField0_ |= 0x00000002;
              }
              items_.add(input.readMessage(com.protobuf.TestCreateItem.test_create_item.Item.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.TestCreateItem.internal_static_test_create_item_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.TestCreateItem.internal_static_test_create_item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.TestCreateItem.test_create_item.class, com.protobuf.TestCreateItem.test_create_item.Builder.class);
    }

    public static com.google.protobuf.Parser<test_create_item> PARSER =
        new com.google.protobuf.AbstractParser<test_create_item>() {
      public test_create_item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new test_create_item(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<test_create_item> getParserForType() {
      return PARSER;
    }

    public interface ItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:test_create_item.Item)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required uint32 item_type = 1;</code>
       */
      boolean hasItemType();
      /**
       * <code>required uint32 item_type = 1;</code>
       */
      int getItemType();

      /**
       * <code>required uint32 item_number = 2;</code>
       */
      boolean hasItemNumber();
      /**
       * <code>required uint32 item_number = 2;</code>
       */
      int getItemNumber();
    }
    /**
     * Protobuf type {@code test_create_item.Item}
     */
    public static final class Item extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:test_create_item.Item)
        ItemOrBuilder {
      // Use Item.newBuilder() to construct.
      private Item(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Item(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Item defaultInstance;
      public static Item getDefaultInstance() {
        return defaultInstance;
      }

      public Item getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Item(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                itemType_ = input.readUInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                itemNumber_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.TestCreateItem.internal_static_test_create_item_Item_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.TestCreateItem.internal_static_test_create_item_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.TestCreateItem.test_create_item.Item.class, com.protobuf.TestCreateItem.test_create_item.Item.Builder.class);
      }

      public static com.google.protobuf.Parser<Item> PARSER =
          new com.google.protobuf.AbstractParser<Item>() {
        public Item parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Item(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Item> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int ITEM_TYPE_FIELD_NUMBER = 1;
      private int itemType_;
      /**
       * <code>required uint32 item_type = 1;</code>
       */
      public boolean hasItemType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 item_type = 1;</code>
       */
      public int getItemType() {
        return itemType_;
      }

      public static final int ITEM_NUMBER_FIELD_NUMBER = 2;
      private int itemNumber_;
      /**
       * <code>required uint32 item_number = 2;</code>
       */
      public boolean hasItemNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 item_number = 2;</code>
       */
      public int getItemNumber() {
        return itemNumber_;
      }

      private void initFields() {
        itemType_ = 0;
        itemNumber_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasItemType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasItemNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, itemType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(2, itemNumber_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, itemType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, itemNumber_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.protobuf.TestCreateItem.test_create_item.Item parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuf.TestCreateItem.test_create_item.Item parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuf.TestCreateItem.test_create_item.Item parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuf.TestCreateItem.test_create_item.Item parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuf.TestCreateItem.test_create_item.Item parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.protobuf.TestCreateItem.test_create_item.Item parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.protobuf.TestCreateItem.test_create_item.Item parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.protobuf.TestCreateItem.test_create_item.Item parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.protobuf.TestCreateItem.test_create_item.Item parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.protobuf.TestCreateItem.test_create_item.Item parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.protobuf.TestCreateItem.test_create_item.Item prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code test_create_item.Item}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:test_create_item.Item)
          com.protobuf.TestCreateItem.test_create_item.ItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.protobuf.TestCreateItem.internal_static_test_create_item_Item_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.protobuf.TestCreateItem.internal_static_test_create_item_Item_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.protobuf.TestCreateItem.test_create_item.Item.class, com.protobuf.TestCreateItem.test_create_item.Item.Builder.class);
        }

        // Construct using com.protobuf.TestCreateItem.test_create_item.Item.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          itemType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          itemNumber_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.protobuf.TestCreateItem.internal_static_test_create_item_Item_descriptor;
        }

        public com.protobuf.TestCreateItem.test_create_item.Item getDefaultInstanceForType() {
          return com.protobuf.TestCreateItem.test_create_item.Item.getDefaultInstance();
        }

        public com.protobuf.TestCreateItem.test_create_item.Item build() {
          com.protobuf.TestCreateItem.test_create_item.Item result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.protobuf.TestCreateItem.test_create_item.Item buildPartial() {
          com.protobuf.TestCreateItem.test_create_item.Item result = new com.protobuf.TestCreateItem.test_create_item.Item(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.itemType_ = itemType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.itemNumber_ = itemNumber_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.protobuf.TestCreateItem.test_create_item.Item) {
            return mergeFrom((com.protobuf.TestCreateItem.test_create_item.Item)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.protobuf.TestCreateItem.test_create_item.Item other) {
          if (other == com.protobuf.TestCreateItem.test_create_item.Item.getDefaultInstance()) return this;
          if (other.hasItemType()) {
            setItemType(other.getItemType());
          }
          if (other.hasItemNumber()) {
            setItemNumber(other.getItemNumber());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasItemType()) {
            
            return false;
          }
          if (!hasItemNumber()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.protobuf.TestCreateItem.test_create_item.Item parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.protobuf.TestCreateItem.test_create_item.Item) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int itemType_ ;
        /**
         * <code>required uint32 item_type = 1;</code>
         */
        public boolean hasItemType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 item_type = 1;</code>
         */
        public int getItemType() {
          return itemType_;
        }
        /**
         * <code>required uint32 item_type = 1;</code>
         */
        public Builder setItemType(int value) {
          bitField0_ |= 0x00000001;
          itemType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 item_type = 1;</code>
         */
        public Builder clearItemType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          itemType_ = 0;
          onChanged();
          return this;
        }

        private int itemNumber_ ;
        /**
         * <code>required uint32 item_number = 2;</code>
         */
        public boolean hasItemNumber() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required uint32 item_number = 2;</code>
         */
        public int getItemNumber() {
          return itemNumber_;
        }
        /**
         * <code>required uint32 item_number = 2;</code>
         */
        public Builder setItemNumber(int value) {
          bitField0_ |= 0x00000002;
          itemNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 item_number = 2;</code>
         */
        public Builder clearItemNumber() {
          bitField0_ = (bitField0_ & ~0x00000002);
          itemNumber_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:test_create_item.Item)
      }

      static {
        defaultInstance = new Item(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:test_create_item.Item)
    }

    private int bitField0_;
    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>required uint32 player_id = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 player_id = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int ITEMS_FIELD_NUMBER = 2;
    private java.util.List<com.protobuf.TestCreateItem.test_create_item.Item> items_;
    /**
     * <code>repeated .test_create_item.Item items = 2;</code>
     */
    public java.util.List<com.protobuf.TestCreateItem.test_create_item.Item> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .test_create_item.Item items = 2;</code>
     */
    public java.util.List<? extends com.protobuf.TestCreateItem.test_create_item.ItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .test_create_item.Item items = 2;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .test_create_item.Item items = 2;</code>
     */
    public com.protobuf.TestCreateItem.test_create_item.Item getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .test_create_item.Item items = 2;</code>
     */
    public com.protobuf.TestCreateItem.test_create_item.ItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      playerId_ = 0;
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, playerId_);
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(2, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, playerId_);
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.TestCreateItem.test_create_item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateItem.test_create_item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateItem.test_create_item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateItem.test_create_item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateItem.test_create_item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateItem.test_create_item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateItem.test_create_item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.TestCreateItem.test_create_item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateItem.test_create_item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateItem.test_create_item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.TestCreateItem.test_create_item prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test_create_item}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test_create_item)
        com.protobuf.TestCreateItem.test_create_itemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.TestCreateItem.internal_static_test_create_item_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.TestCreateItem.internal_static_test_create_item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.TestCreateItem.test_create_item.class, com.protobuf.TestCreateItem.test_create_item.Builder.class);
      }

      // Construct using com.protobuf.TestCreateItem.test_create_item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.TestCreateItem.internal_static_test_create_item_descriptor;
      }

      public com.protobuf.TestCreateItem.test_create_item getDefaultInstanceForType() {
        return com.protobuf.TestCreateItem.test_create_item.getDefaultInstance();
      }

      public com.protobuf.TestCreateItem.test_create_item build() {
        com.protobuf.TestCreateItem.test_create_item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.TestCreateItem.test_create_item buildPartial() {
        com.protobuf.TestCreateItem.test_create_item result = new com.protobuf.TestCreateItem.test_create_item(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.TestCreateItem.test_create_item) {
          return mergeFrom((com.protobuf.TestCreateItem.test_create_item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.TestCreateItem.test_create_item other) {
        if (other == com.protobuf.TestCreateItem.test_create_item.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.TestCreateItem.test_create_item parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.TestCreateItem.test_create_item) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int playerId_ ;
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.protobuf.TestCreateItem.test_create_item.Item> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = new java.util.ArrayList<com.protobuf.TestCreateItem.test_create_item.Item>(items_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.protobuf.TestCreateItem.test_create_item.Item, com.protobuf.TestCreateItem.test_create_item.Item.Builder, com.protobuf.TestCreateItem.test_create_item.ItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public java.util.List<com.protobuf.TestCreateItem.test_create_item.Item> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public com.protobuf.TestCreateItem.test_create_item.Item getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public Builder setItems(
          int index, com.protobuf.TestCreateItem.test_create_item.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public Builder setItems(
          int index, com.protobuf.TestCreateItem.test_create_item.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public Builder addItems(com.protobuf.TestCreateItem.test_create_item.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public Builder addItems(
          int index, com.protobuf.TestCreateItem.test_create_item.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public Builder addItems(
          com.protobuf.TestCreateItem.test_create_item.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public Builder addItems(
          int index, com.protobuf.TestCreateItem.test_create_item.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.protobuf.TestCreateItem.test_create_item.Item> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public com.protobuf.TestCreateItem.test_create_item.Item.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public com.protobuf.TestCreateItem.test_create_item.ItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public java.util.List<? extends com.protobuf.TestCreateItem.test_create_item.ItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public com.protobuf.TestCreateItem.test_create_item.Item.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.protobuf.TestCreateItem.test_create_item.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public com.protobuf.TestCreateItem.test_create_item.Item.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.protobuf.TestCreateItem.test_create_item.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .test_create_item.Item items = 2;</code>
       */
      public java.util.List<com.protobuf.TestCreateItem.test_create_item.Item.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.protobuf.TestCreateItem.test_create_item.Item, com.protobuf.TestCreateItem.test_create_item.Item.Builder, com.protobuf.TestCreateItem.test_create_item.ItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.protobuf.TestCreateItem.test_create_item.Item, com.protobuf.TestCreateItem.test_create_item.Item.Builder, com.protobuf.TestCreateItem.test_create_item.ItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:test_create_item)
    }

    static {
      defaultInstance = new test_create_item(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test_create_item)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_create_item_request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_create_item_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_create_item_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_create_item_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_create_item_Item_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_create_item_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026test_create_item.proto\"-\n\030test_create_" +
      "item_request\022\021\n\titem_type\030\001 \002(\r\"|\n\020test_" +
      "create_item\022\021\n\tplayer_id\030\001 \002(\r\022%\n\005items\030" +
      "\002 \003(\0132\026.test_create_item.Item\032.\n\004Item\022\021\n" +
      "\titem_type\030\001 \002(\r\022\023\n\013item_number\030\002 \002(\rB\016\n" +
      "\014com.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_test_create_item_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_create_item_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_create_item_request_descriptor,
        new java.lang.String[] { "ItemType", });
    internal_static_test_create_item_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_create_item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_create_item_descriptor,
        new java.lang.String[] { "PlayerId", "Items", });
    internal_static_test_create_item_Item_descriptor =
      internal_static_test_create_item_descriptor.getNestedTypes().get(0);
    internal_static_test_create_item_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_create_item_Item_descriptor,
        new java.lang.String[] { "ItemType", "ItemNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
