// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_create_soldier.proto

package com.protobuf;

public final class TestCreateSoldier {
  private TestCreateSoldier() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface test_create_soldier_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test_create_soldier_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 soldier_type = 1;</code>
     */
    boolean hasSoldierType();
    /**
     * <code>required uint32 soldier_type = 1;</code>
     */
    int getSoldierType();
  }
  /**
   * Protobuf type {@code test_create_soldier_request}
   *
   * <pre>
   * 作弊：瞬间移动
   * </pre>
   */
  public static final class test_create_soldier_request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:test_create_soldier_request)
      test_create_soldier_requestOrBuilder {
    // Use test_create_soldier_request.newBuilder() to construct.
    private test_create_soldier_request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private test_create_soldier_request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final test_create_soldier_request defaultInstance;
    public static test_create_soldier_request getDefaultInstance() {
      return defaultInstance;
    }

    public test_create_soldier_request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private test_create_soldier_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              soldierType_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.TestCreateSoldier.test_create_soldier_request.class, com.protobuf.TestCreateSoldier.test_create_soldier_request.Builder.class);
    }

    public static com.google.protobuf.Parser<test_create_soldier_request> PARSER =
        new com.google.protobuf.AbstractParser<test_create_soldier_request>() {
      public test_create_soldier_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new test_create_soldier_request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<test_create_soldier_request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SOLDIER_TYPE_FIELD_NUMBER = 1;
    private int soldierType_;
    /**
     * <code>required uint32 soldier_type = 1;</code>
     */
    public boolean hasSoldierType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 soldier_type = 1;</code>
     */
    public int getSoldierType() {
      return soldierType_;
    }

    private void initFields() {
      soldierType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSoldierType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, soldierType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, soldierType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.TestCreateSoldier.test_create_soldier_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.TestCreateSoldier.test_create_soldier_request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test_create_soldier_request}
     *
     * <pre>
     * 作弊：瞬间移动
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test_create_soldier_request)
        com.protobuf.TestCreateSoldier.test_create_soldier_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.TestCreateSoldier.test_create_soldier_request.class, com.protobuf.TestCreateSoldier.test_create_soldier_request.Builder.class);
      }

      // Construct using com.protobuf.TestCreateSoldier.test_create_soldier_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        soldierType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_request_descriptor;
      }

      public com.protobuf.TestCreateSoldier.test_create_soldier_request getDefaultInstanceForType() {
        return com.protobuf.TestCreateSoldier.test_create_soldier_request.getDefaultInstance();
      }

      public com.protobuf.TestCreateSoldier.test_create_soldier_request build() {
        com.protobuf.TestCreateSoldier.test_create_soldier_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.TestCreateSoldier.test_create_soldier_request buildPartial() {
        com.protobuf.TestCreateSoldier.test_create_soldier_request result = new com.protobuf.TestCreateSoldier.test_create_soldier_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.soldierType_ = soldierType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.TestCreateSoldier.test_create_soldier_request) {
          return mergeFrom((com.protobuf.TestCreateSoldier.test_create_soldier_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.TestCreateSoldier.test_create_soldier_request other) {
        if (other == com.protobuf.TestCreateSoldier.test_create_soldier_request.getDefaultInstance()) return this;
        if (other.hasSoldierType()) {
          setSoldierType(other.getSoldierType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSoldierType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.TestCreateSoldier.test_create_soldier_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.TestCreateSoldier.test_create_soldier_request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int soldierType_ ;
      /**
       * <code>required uint32 soldier_type = 1;</code>
       */
      public boolean hasSoldierType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 soldier_type = 1;</code>
       */
      public int getSoldierType() {
        return soldierType_;
      }
      /**
       * <code>required uint32 soldier_type = 1;</code>
       */
      public Builder setSoldierType(int value) {
        bitField0_ |= 0x00000001;
        soldierType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 soldier_type = 1;</code>
       */
      public Builder clearSoldierType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        soldierType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test_create_soldier_request)
    }

    static {
      defaultInstance = new test_create_soldier_request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test_create_soldier_request)
  }

  public interface test_create_soldierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test_create_soldier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 player_id = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required uint32 player_id = 1;</code>
     */
    int getPlayerId();

    /**
     * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
     */
    java.util.List<com.protobuf.TestCreateSoldier.test_create_soldier.Soldier> 
        getSoldiersList();
    /**
     * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
     */
    com.protobuf.TestCreateSoldier.test_create_soldier.Soldier getSoldiers(int index);
    /**
     * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
     */
    int getSoldiersCount();
    /**
     * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
     */
    java.util.List<? extends com.protobuf.TestCreateSoldier.test_create_soldier.SoldierOrBuilder> 
        getSoldiersOrBuilderList();
    /**
     * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
     */
    com.protobuf.TestCreateSoldier.test_create_soldier.SoldierOrBuilder getSoldiersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code test_create_soldier}
   */
  public static final class test_create_soldier extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:test_create_soldier)
      test_create_soldierOrBuilder {
    // Use test_create_soldier.newBuilder() to construct.
    private test_create_soldier(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private test_create_soldier(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final test_create_soldier defaultInstance;
    public static test_create_soldier getDefaultInstance() {
      return defaultInstance;
    }

    public test_create_soldier getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private test_create_soldier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readUInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                soldiers_ = new java.util.ArrayList<com.protobuf.TestCreateSoldier.test_create_soldier.Soldier>();
                mutable_bitField0_ |= 0x00000002;
              }
              soldiers_.add(input.readMessage(com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          soldiers_ = java.util.Collections.unmodifiableList(soldiers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.TestCreateSoldier.test_create_soldier.class, com.protobuf.TestCreateSoldier.test_create_soldier.Builder.class);
    }

    public static com.google.protobuf.Parser<test_create_soldier> PARSER =
        new com.google.protobuf.AbstractParser<test_create_soldier>() {
      public test_create_soldier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new test_create_soldier(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<test_create_soldier> getParserForType() {
      return PARSER;
    }

    public interface SoldierOrBuilder extends
        // @@protoc_insertion_point(interface_extends:test_create_soldier.Soldier)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required uint32 soldier_type = 1;</code>
       */
      boolean hasSoldierType();
      /**
       * <code>required uint32 soldier_type = 1;</code>
       */
      int getSoldierType();

      /**
       * <code>required uint32 soldier_number = 2;</code>
       */
      boolean hasSoldierNumber();
      /**
       * <code>required uint32 soldier_number = 2;</code>
       */
      int getSoldierNumber();
    }
    /**
     * Protobuf type {@code test_create_soldier.Soldier}
     */
    public static final class Soldier extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:test_create_soldier.Soldier)
        SoldierOrBuilder {
      // Use Soldier.newBuilder() to construct.
      private Soldier(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Soldier(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Soldier defaultInstance;
      public static Soldier getDefaultInstance() {
        return defaultInstance;
      }

      public Soldier getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Soldier(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                soldierType_ = input.readUInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                soldierNumber_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_Soldier_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_Soldier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.class, com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder.class);
      }

      public static com.google.protobuf.Parser<Soldier> PARSER =
          new com.google.protobuf.AbstractParser<Soldier>() {
        public Soldier parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Soldier(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Soldier> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int SOLDIER_TYPE_FIELD_NUMBER = 1;
      private int soldierType_;
      /**
       * <code>required uint32 soldier_type = 1;</code>
       */
      public boolean hasSoldierType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 soldier_type = 1;</code>
       */
      public int getSoldierType() {
        return soldierType_;
      }

      public static final int SOLDIER_NUMBER_FIELD_NUMBER = 2;
      private int soldierNumber_;
      /**
       * <code>required uint32 soldier_number = 2;</code>
       */
      public boolean hasSoldierNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 soldier_number = 2;</code>
       */
      public int getSoldierNumber() {
        return soldierNumber_;
      }

      private void initFields() {
        soldierType_ = 0;
        soldierNumber_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasSoldierType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSoldierNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, soldierType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(2, soldierNumber_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, soldierType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, soldierNumber_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.protobuf.TestCreateSoldier.test_create_soldier.Soldier prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code test_create_soldier.Soldier}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:test_create_soldier.Soldier)
          com.protobuf.TestCreateSoldier.test_create_soldier.SoldierOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_Soldier_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_Soldier_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.class, com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder.class);
        }

        // Construct using com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          soldierType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          soldierNumber_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_Soldier_descriptor;
        }

        public com.protobuf.TestCreateSoldier.test_create_soldier.Soldier getDefaultInstanceForType() {
          return com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.getDefaultInstance();
        }

        public com.protobuf.TestCreateSoldier.test_create_soldier.Soldier build() {
          com.protobuf.TestCreateSoldier.test_create_soldier.Soldier result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.protobuf.TestCreateSoldier.test_create_soldier.Soldier buildPartial() {
          com.protobuf.TestCreateSoldier.test_create_soldier.Soldier result = new com.protobuf.TestCreateSoldier.test_create_soldier.Soldier(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.soldierType_ = soldierType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.soldierNumber_ = soldierNumber_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.protobuf.TestCreateSoldier.test_create_soldier.Soldier) {
            return mergeFrom((com.protobuf.TestCreateSoldier.test_create_soldier.Soldier)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.protobuf.TestCreateSoldier.test_create_soldier.Soldier other) {
          if (other == com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.getDefaultInstance()) return this;
          if (other.hasSoldierType()) {
            setSoldierType(other.getSoldierType());
          }
          if (other.hasSoldierNumber()) {
            setSoldierNumber(other.getSoldierNumber());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasSoldierType()) {
            
            return false;
          }
          if (!hasSoldierNumber()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.protobuf.TestCreateSoldier.test_create_soldier.Soldier parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.protobuf.TestCreateSoldier.test_create_soldier.Soldier) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int soldierType_ ;
        /**
         * <code>required uint32 soldier_type = 1;</code>
         */
        public boolean hasSoldierType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 soldier_type = 1;</code>
         */
        public int getSoldierType() {
          return soldierType_;
        }
        /**
         * <code>required uint32 soldier_type = 1;</code>
         */
        public Builder setSoldierType(int value) {
          bitField0_ |= 0x00000001;
          soldierType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 soldier_type = 1;</code>
         */
        public Builder clearSoldierType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          soldierType_ = 0;
          onChanged();
          return this;
        }

        private int soldierNumber_ ;
        /**
         * <code>required uint32 soldier_number = 2;</code>
         */
        public boolean hasSoldierNumber() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required uint32 soldier_number = 2;</code>
         */
        public int getSoldierNumber() {
          return soldierNumber_;
        }
        /**
         * <code>required uint32 soldier_number = 2;</code>
         */
        public Builder setSoldierNumber(int value) {
          bitField0_ |= 0x00000002;
          soldierNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 soldier_number = 2;</code>
         */
        public Builder clearSoldierNumber() {
          bitField0_ = (bitField0_ & ~0x00000002);
          soldierNumber_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:test_create_soldier.Soldier)
      }

      static {
        defaultInstance = new Soldier(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:test_create_soldier.Soldier)
    }

    private int bitField0_;
    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>required uint32 player_id = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 player_id = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int SOLDIERS_FIELD_NUMBER = 2;
    private java.util.List<com.protobuf.TestCreateSoldier.test_create_soldier.Soldier> soldiers_;
    /**
     * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
     */
    public java.util.List<com.protobuf.TestCreateSoldier.test_create_soldier.Soldier> getSoldiersList() {
      return soldiers_;
    }
    /**
     * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
     */
    public java.util.List<? extends com.protobuf.TestCreateSoldier.test_create_soldier.SoldierOrBuilder> 
        getSoldiersOrBuilderList() {
      return soldiers_;
    }
    /**
     * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
     */
    public int getSoldiersCount() {
      return soldiers_.size();
    }
    /**
     * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
     */
    public com.protobuf.TestCreateSoldier.test_create_soldier.Soldier getSoldiers(int index) {
      return soldiers_.get(index);
    }
    /**
     * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
     */
    public com.protobuf.TestCreateSoldier.test_create_soldier.SoldierOrBuilder getSoldiersOrBuilder(
        int index) {
      return soldiers_.get(index);
    }

    private void initFields() {
      playerId_ = 0;
      soldiers_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSoldiersCount(); i++) {
        if (!getSoldiers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, playerId_);
      }
      for (int i = 0; i < soldiers_.size(); i++) {
        output.writeMessage(2, soldiers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, playerId_);
      }
      for (int i = 0; i < soldiers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, soldiers_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.TestCreateSoldier.test_create_soldier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.TestCreateSoldier.test_create_soldier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.TestCreateSoldier.test_create_soldier prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test_create_soldier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test_create_soldier)
        com.protobuf.TestCreateSoldier.test_create_soldierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.TestCreateSoldier.test_create_soldier.class, com.protobuf.TestCreateSoldier.test_create_soldier.Builder.class);
      }

      // Construct using com.protobuf.TestCreateSoldier.test_create_soldier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSoldiersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (soldiersBuilder_ == null) {
          soldiers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          soldiersBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.TestCreateSoldier.internal_static_test_create_soldier_descriptor;
      }

      public com.protobuf.TestCreateSoldier.test_create_soldier getDefaultInstanceForType() {
        return com.protobuf.TestCreateSoldier.test_create_soldier.getDefaultInstance();
      }

      public com.protobuf.TestCreateSoldier.test_create_soldier build() {
        com.protobuf.TestCreateSoldier.test_create_soldier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.TestCreateSoldier.test_create_soldier buildPartial() {
        com.protobuf.TestCreateSoldier.test_create_soldier result = new com.protobuf.TestCreateSoldier.test_create_soldier(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (soldiersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            soldiers_ = java.util.Collections.unmodifiableList(soldiers_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.soldiers_ = soldiers_;
        } else {
          result.soldiers_ = soldiersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.TestCreateSoldier.test_create_soldier) {
          return mergeFrom((com.protobuf.TestCreateSoldier.test_create_soldier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.TestCreateSoldier.test_create_soldier other) {
        if (other == com.protobuf.TestCreateSoldier.test_create_soldier.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (soldiersBuilder_ == null) {
          if (!other.soldiers_.isEmpty()) {
            if (soldiers_.isEmpty()) {
              soldiers_ = other.soldiers_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSoldiersIsMutable();
              soldiers_.addAll(other.soldiers_);
            }
            onChanged();
          }
        } else {
          if (!other.soldiers_.isEmpty()) {
            if (soldiersBuilder_.isEmpty()) {
              soldiersBuilder_.dispose();
              soldiersBuilder_ = null;
              soldiers_ = other.soldiers_;
              bitField0_ = (bitField0_ & ~0x00000002);
              soldiersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSoldiersFieldBuilder() : null;
            } else {
              soldiersBuilder_.addAllMessages(other.soldiers_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        for (int i = 0; i < getSoldiersCount(); i++) {
          if (!getSoldiers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.TestCreateSoldier.test_create_soldier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.TestCreateSoldier.test_create_soldier) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int playerId_ ;
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 player_id = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.protobuf.TestCreateSoldier.test_create_soldier.Soldier> soldiers_ =
        java.util.Collections.emptyList();
      private void ensureSoldiersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          soldiers_ = new java.util.ArrayList<com.protobuf.TestCreateSoldier.test_create_soldier.Soldier>(soldiers_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.protobuf.TestCreateSoldier.test_create_soldier.Soldier, com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder, com.protobuf.TestCreateSoldier.test_create_soldier.SoldierOrBuilder> soldiersBuilder_;

      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public java.util.List<com.protobuf.TestCreateSoldier.test_create_soldier.Soldier> getSoldiersList() {
        if (soldiersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(soldiers_);
        } else {
          return soldiersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public int getSoldiersCount() {
        if (soldiersBuilder_ == null) {
          return soldiers_.size();
        } else {
          return soldiersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public com.protobuf.TestCreateSoldier.test_create_soldier.Soldier getSoldiers(int index) {
        if (soldiersBuilder_ == null) {
          return soldiers_.get(index);
        } else {
          return soldiersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public Builder setSoldiers(
          int index, com.protobuf.TestCreateSoldier.test_create_soldier.Soldier value) {
        if (soldiersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSoldiersIsMutable();
          soldiers_.set(index, value);
          onChanged();
        } else {
          soldiersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public Builder setSoldiers(
          int index, com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder builderForValue) {
        if (soldiersBuilder_ == null) {
          ensureSoldiersIsMutable();
          soldiers_.set(index, builderForValue.build());
          onChanged();
        } else {
          soldiersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public Builder addSoldiers(com.protobuf.TestCreateSoldier.test_create_soldier.Soldier value) {
        if (soldiersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSoldiersIsMutable();
          soldiers_.add(value);
          onChanged();
        } else {
          soldiersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public Builder addSoldiers(
          int index, com.protobuf.TestCreateSoldier.test_create_soldier.Soldier value) {
        if (soldiersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSoldiersIsMutable();
          soldiers_.add(index, value);
          onChanged();
        } else {
          soldiersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public Builder addSoldiers(
          com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder builderForValue) {
        if (soldiersBuilder_ == null) {
          ensureSoldiersIsMutable();
          soldiers_.add(builderForValue.build());
          onChanged();
        } else {
          soldiersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public Builder addSoldiers(
          int index, com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder builderForValue) {
        if (soldiersBuilder_ == null) {
          ensureSoldiersIsMutable();
          soldiers_.add(index, builderForValue.build());
          onChanged();
        } else {
          soldiersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public Builder addAllSoldiers(
          java.lang.Iterable<? extends com.protobuf.TestCreateSoldier.test_create_soldier.Soldier> values) {
        if (soldiersBuilder_ == null) {
          ensureSoldiersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, soldiers_);
          onChanged();
        } else {
          soldiersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public Builder clearSoldiers() {
        if (soldiersBuilder_ == null) {
          soldiers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          soldiersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public Builder removeSoldiers(int index) {
        if (soldiersBuilder_ == null) {
          ensureSoldiersIsMutable();
          soldiers_.remove(index);
          onChanged();
        } else {
          soldiersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder getSoldiersBuilder(
          int index) {
        return getSoldiersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public com.protobuf.TestCreateSoldier.test_create_soldier.SoldierOrBuilder getSoldiersOrBuilder(
          int index) {
        if (soldiersBuilder_ == null) {
          return soldiers_.get(index);  } else {
          return soldiersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public java.util.List<? extends com.protobuf.TestCreateSoldier.test_create_soldier.SoldierOrBuilder> 
           getSoldiersOrBuilderList() {
        if (soldiersBuilder_ != null) {
          return soldiersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(soldiers_);
        }
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder addSoldiersBuilder() {
        return getSoldiersFieldBuilder().addBuilder(
            com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.getDefaultInstance());
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder addSoldiersBuilder(
          int index) {
        return getSoldiersFieldBuilder().addBuilder(
            index, com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.getDefaultInstance());
      }
      /**
       * <code>repeated .test_create_soldier.Soldier soldiers = 2;</code>
       */
      public java.util.List<com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder> 
           getSoldiersBuilderList() {
        return getSoldiersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.protobuf.TestCreateSoldier.test_create_soldier.Soldier, com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder, com.protobuf.TestCreateSoldier.test_create_soldier.SoldierOrBuilder> 
          getSoldiersFieldBuilder() {
        if (soldiersBuilder_ == null) {
          soldiersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.protobuf.TestCreateSoldier.test_create_soldier.Soldier, com.protobuf.TestCreateSoldier.test_create_soldier.Soldier.Builder, com.protobuf.TestCreateSoldier.test_create_soldier.SoldierOrBuilder>(
                  soldiers_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          soldiers_ = null;
        }
        return soldiersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:test_create_soldier)
    }

    static {
      defaultInstance = new test_create_soldier(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test_create_soldier)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_create_soldier_request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_create_soldier_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_create_soldier_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_create_soldier_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_create_soldier_Soldier_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_create_soldier_Soldier_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031test_create_soldier.proto\"3\n\033test_crea" +
      "te_soldier_request\022\024\n\014soldier_type\030\001 \002(\r" +
      "\"\221\001\n\023test_create_soldier\022\021\n\tplayer_id\030\001 " +
      "\002(\r\022.\n\010soldiers\030\002 \003(\0132\034.test_create_sold" +
      "ier.Soldier\0327\n\007Soldier\022\024\n\014soldier_type\030\001" +
      " \002(\r\022\026\n\016soldier_number\030\002 \002(\rB\016\n\014com.prot" +
      "obuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_test_create_soldier_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_create_soldier_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_create_soldier_request_descriptor,
        new java.lang.String[] { "SoldierType", });
    internal_static_test_create_soldier_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_create_soldier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_create_soldier_descriptor,
        new java.lang.String[] { "PlayerId", "Soldiers", });
    internal_static_test_create_soldier_Soldier_descriptor =
      internal_static_test_create_soldier_descriptor.getNestedTypes().get(0);
    internal_static_test_create_soldier_Soldier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_create_soldier_Soldier_descriptor,
        new java.lang.String[] { "SoldierType", "SoldierNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
