--[[ SheetEditor v1.0
物品id,物品名称(name),物品描述(desc),能否直接使用,道具类型,图标(icon),绑定类型(isbind),最大叠加数量(maxCount),出售价格(price),使用最小官职(minGovernmentLevel),使用最小主城等级(minCityLevel),加速效果（speedup）,效果(effect),宝箱内容,掉落次数上限,
*id,name,desc,isuse,itemType,icon,isbind,maxCount,price,minGovernmentLevel,minCityLevel,speedup,effect:array,chestitems,maxDropnum,
sorted = { 0, 'a' }
--]]

local M = {
    [50101] = {
        id = 50101,
        name = "徭役令",
        desc = "提升当前所有生产队生产速度的10%，可重复使用",
        isuse = 1,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 1,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        speedup = "2,10",
    },
    [50201] = {
        id = 50201,
        name = "虎符",
        desc = "提升当前所有征兵队列征兵速度的10%，可重复使用",
        isuse = 1,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 2,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        speedup = "2,10",
    },
    [50301] = {
        id = 50301,
        name = "战鼓",
        desc = "提升当前所有训练队列训练速度的10%，可重复使用",
        isuse = 1,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 2,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        speedup = "2,10",
    },
    [50401] = {
        id = 50401,
        name = "银宝箱",
        desc = "打开后随机获得一定数量的粮食/木材/石料/铜币/元气玉中的任一种资源",
        isuse = 1,
        itemType = 3,
        isbind = 0,
        maxCount = 999,
        price = 2,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
        chestitems = "1,2500;2,2500;3,2500;4,2500",
        maxDropnum = 1,
    },
    [50402] = {
        id = 50402,
        name = "金宝箱",
        desc = "打开后随机获得一名武将或一定数量的士兵",
        isuse = 1,
        itemType = 3,
        isbind = 0,
        maxCount = 999,
        price = 2,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
        chestitems = "3,2500;4,2500;5,2500;6,2500",
        maxDropnum = 1,
    },
    [50502] = {
        id = 50502,
        name = "女儿红",
        desc = "招募一名武将，需要消耗一女儿红",
        isuse = 0,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 8,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
    },
    [50601] = {
        id = 50601,
        name = "华佗再世",
        desc = "提升当前医疗馆中所有武将治疗速度的10%，可重复使用",
        isuse = 1,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 8,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        speedup = "2,10",
    },
    [50702] = {
        id = 50702,
        name = "遁甲天书",
        desc = "当一支部队被击败时，该部队30%的士兵幸存，直接返还到主城，持续2小时，效果时间可累积",
        isuse = 1,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 10,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
    },
    [50703] = {
        id = 50703,
        name = "孙子兵法",
        desc = "提升所有部队的攻击力10%，防御力10%，持续2小时，效果时间可累积",
        isuse = 1,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 10,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
    },
    [50704] = {
        id = 50704,
        name = "木牛流马",
        desc = "立刻补满一支部队的粮食，需消耗一个木牛流马",
        isuse = 0,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 10,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
    },
    [50705] = {
        id = 50705,
        name = "孟德新书",
        desc = "立刻补满一支部队的士气，需消耗一本孟德新书",
        isuse = 0,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 10,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
    },
    [50706] = {
        id = 50706,
        name = "金蝉脱壳",
        desc = "当部队被击败时，该部队主将不会受伤，直接回到主城，持续2小时，效果时间可累积",
        isuse = 1,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 10,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
    },
    [50707] = {
        id = 50707,
        name = "瞒天过海",
        desc = "隐藏出征的部队踪影，敌人不可见，被敌人部队碰见会打破隐身状态，持续2小时，效果时间可累积",
        isuse = 1,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 10,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
    },
    [50708] = {
        id = 50708,
        name = "回城令",
        desc = "使一支自己的部队立刻返回主城，需消耗一个回城令",
        isuse = 0,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 10,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
    },
    [50709] = {
        id = 50709,
        name = "补兵令",
        desc = "立刻补满一支部队的兵力，需消耗一个补兵令",
        isuse = 0,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 10,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        effect = { 100 },
    },
    [50710] = {
        id = 50710,
        name = "洛书",
        desc = "提升当前官职升级速度的10%，可重复使用",
        isuse = 1,
        itemType = 1,
        isbind = 0,
        maxCount = 999,
        price = 10,
        minGovernmentLevel = 1,
        minCityLevel = 1,
        speedup = "2,10",
    },
    [50801] = {
        id = 50801,
        name = "粮食",
        desc = "资源：粮食",
        itemType = 2,
    },
    [50802] = {
        id = 50802,
        name = "木材",
        desc = "资源：木材",
        itemType = 2,
    },
    [50803] = {
        id = 50803,
        name = "石料",
        desc = "资源：石料",
        itemType = 2,
    },
    [50804] = {
        id = 50804,
        name = "铜币",
        desc = "资源：铜币",
        itemType = 2,
    },
    [50805] = {
        id = 50805,
        name = "元气玉",
        desc = "资源：元气玉",
        itemType = 2,
    },
    [50806] = {
        id = 50806,
        name = "元宝",
        desc = "资源：元宝",
        itemType = 2,
    },
}
return M
