--[[ SheetEditor v1.0
星级（*level）,统率系数（commanderRatio）,武力系数（forceRatio）,智力系数（brainsRatio）,体质（constitutionRatio）,士气恢复速度（energySpeed）,兵力（troopsRatio）,
*level,commanderRatio,forceRatio,brainsRatio,constitutionRatio,energySpeed,troopsRatio,
sorted = { 0, 'a' }
--]]

local M = {
    [1] = {
        level = 1,
        commanderRatio = 1.00,
        forceRatio = 1.00,
        brainsRatio = 1.00,
        constitutionRatio = 1,
        energySpeed = 90,
        troopsRatio = 1,
    },
    [2] = {
        level = 2,
        commanderRatio = 1.06,
        forceRatio = 1.06,
        brainsRatio = 1.06,
        constitutionRatio = 1.1,
        energySpeed = 45,
        troopsRatio = 2,
    },
    [3] = {
        level = 3,
        commanderRatio = 1.12,
        forceRatio = 1.12,
        brainsRatio = 1.12,
        constitutionRatio = 1.2,
        energySpeed = 45,
        troopsRatio = 3,
    },
    [4] = {
        level = 4,
        commanderRatio = 1.19,
        forceRatio = 1.19,
        brainsRatio = 1.19,
        constitutionRatio = 1.3,
        energySpeed = 45,
        troopsRatio = 4,
    },
    [5] = {
        level = 5,
        commanderRatio = 1.26,
        forceRatio = 1.26,
        brainsRatio = 1.26,
        constitutionRatio = 1.4,
        energySpeed = 45,
        troopsRatio = 5,
    },
    [6] = {
        level = 6,
        commanderRatio = 1.34,
        forceRatio = 1.34,
        brainsRatio = 1.34,
        constitutionRatio = 1.5,
        energySpeed = 45,
        troopsRatio = 6,
    },
    [7] = {
        level = 7,
        commanderRatio = 1.42,
        forceRatio = 1.42,
        brainsRatio = 1.42,
        constitutionRatio = 1.6,
        energySpeed = 45,
        troopsRatio = 7,
    },
    [8] = {
        level = 8,
        commanderRatio = 1.50,
        forceRatio = 1.50,
        brainsRatio = 1.50,
        constitutionRatio = 1.7,
        energySpeed = 45,
        troopsRatio = 8,
    },
    [9] = {
        level = 9,
        commanderRatio = 1.59,
        forceRatio = 1.59,
        brainsRatio = 1.59,
        constitutionRatio = 1.8,
        energySpeed = 45,
        troopsRatio = 9,
    },
    [10] = {
        level = 10,
        commanderRatio = 1.69,
        forceRatio = 1.69,
        brainsRatio = 1.69,
        constitutionRatio = 1.9,
        energySpeed = 45,
        troopsRatio = 10,
    },
}
return M
